### Importación de datos

In [131]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

In [100]:
##Ingreso total por cada tienda
Ingreso_total_tienda1 = sum(tienda['Precio'])
Ingreso_total_tienda2 = sum(tienda2['Precio'])
Ingreso_total_tienda3 = sum(tienda3['Precio'])
Ingreso_total_tienda4 = sum(tienda4['Precio'])
print(f'Ingreso total de la tienda 1 es : {Ingreso_total_tienda1}')
print(f'Ingreso total de la tienda 2 es : {Ingreso_total_tienda2}')
print(f'Ingreso total de la tienda 3 es : {Ingreso_total_tienda3}')
print(f'Ingreso total de la tienda 4 es : {Ingreso_total_tienda4}')

Ingreso total de la tienda 1 es : 1150880400.0
Ingreso total de la tienda 2 es : 1116343500.0
Ingreso total de la tienda 3 es : 1098019600.0
Ingreso total de la tienda 4 es : 1038375700.0

# 2. Ventas por categoría

In [101]:
ventas_por_categoria_tienda1 = tienda['Categoría del Producto'].value_counts()
ventas_por_categoria_tienda2 = tienda2['Categoría del Producto'].value_counts()
ventas_por_categoria_tienda3 = tienda3['Categoría del Producto'].value_counts()
ventas_por_categoria_tienda4 = tienda4['Categoría del Producto'].value_counts()

In [102]:
print(f'La cantidad de producto por categoría de la tienda 1: \n{ventas_por_categoria_tienda1}')

La cantidad de producto por categoría de la tienda 1:
Categoría del Producto
Muebles                    465
Electrónicos               448
Juguetes                   324
Electrodomésticos          312
Deportes y diversión       284
Instrumentos musicales     182
Libros                     173
Artículos para el hogar    171
Name: count, dtype: int64

In [103]:
print(f'La cantidad de producto por categoría de la tienda 2: \n{ventas_por_categoria_tienda2}')

La cantidad de producto por categoría de la tienda 2:
Categoría del Producto
Muebles                    442
Electrónicos               422
Juguetes                   313
Electrodomésticos          305
Deportes y diversión       275
Instrumentos musicales     224
Libros                     197
Artículos para el hogar    181
Name: count, dtype: int64

In [104]:
print(f'La cantidad de producto por categoría de la tienda 3: \n{ventas_por_categoria_tienda3}')

La cantidad de producto por categoría de la tienda 3:
Categoría del Producto
Muebles                    499
Electrónicos               451
Juguetes                   315
Electrodomésticos          278
Deportes y diversión       277
Libros                     185
Instrumentos musicales     177
Artículos para el hogar    177
Name: count, dtype: int64

In [105]:
print(f'La cantidad de producto por categoría de la tienda 4: \n{ventas_por_categoria_tienda4}')

La cantidad de producto por categoría de la tienda 4:
Categoría del Producto
Muebles                    480
Electrónicos               451
Juguetes                   338
Deportes y diversión       277
Electrodomésticos          254
Artículos para el hogar    201
Libros                     187
Instrumentos musicales     170
Name: count, dtype: int64

In [123]:
##Ventas agrupadas por Categoría
venta1 = tienda.groupby('Categoría del Producto')[['Precio']].sum().sort_values('Precio',ascending=False)
venta2 = tienda2.groupby('Categoría del Producto')[['Precio']].sum().sort_values('Precio',ascending=False)
venta3 = tienda3.groupby('Categoría del Producto')[['Precio']].sum().sort_values('Precio',ascending=False)
venta4 = tienda4.groupby('Categoría del Producto')[['Precio']].sum().sort_values('Precio',ascending=False)

In [126]:
print(f'Las ventas agrupadas por categoría de la tienda 1: \n{venta1}')

Las ventas por categoría de la tienda 1:
                              Precio
Categoría del Producto
Electrónicos             429493500.0
Electrodomésticos        363685200.0
Muebles                  187633700.0
Instrumentos musicales    91299000.0
Deportes y diversión      39290000.0
Juguetes                  17995700.0
Artículos para el hogar   12698400.0
Libros                     8784900.0

In [128]:
print(f'Las ventas agrupadas por categoría de la tienda 2: \n{venta2}')

Las ventas agrupadas por categoría de la tienda 2:
                              Precio
Categoría del Producto
Electrónicos             410831100.0
Electrodomésticos        348567800.0
Muebles                  176426300.0
Instrumentos musicales   104990300.0
Deportes y diversión      34744500.0
Juguetes                  15945400.0
Artículos para el hogar   14746900.0
Libros                    10091200.0

In [129]:
print(f'Las ventas agrupadas por categoría de la tienda 3: \n{venta3}')

Las ventas agrupadas por categoría de la tienda 3:
                              Precio
Categoría del Producto
Electrónicos             410775800.0
Electrodomésticos        329237900.0
Muebles                  201072100.0
Instrumentos musicales    77380900.0
Deportes y diversión      35593100.0
Juguetes                  19401100.0
Artículos para el hogar   15060000.0
Libros                     9498700.0

In [130]:
print(f'Las ventas agrupadas por categoría de la tienda 4: \n{venta4}')

Las ventas agrupadas por categoría de la tienda 4:
                              Precio
Categoría del Producto
Electrónicos             409476100.0
Electrodomésticos        283260200.0
Muebles                  192528900.0
Instrumentos musicales    75102400.0
Deportes y diversión      33350100.0
Juguetes                  20262200.0
Artículos para el hogar   15074500.0
Libros                     9321300.0

# 3. Calificación promedio de la tienda

In [148]:
promedio_calificacion_tienda1 = tienda['Calificación'].mean().round(2)
promedio_calificacion_tienda2 = tienda2['Calificación'].mean().round(2)
promedio_calificacion_tienda3 = tienda3['Calificación'].mean().round(2)
promedio_calificacion_tienda4 = tienda4['Calificación'].mean().round(2)

In [149]:
print(f' El promedio de calificación de la tienda 1 es: {promedio_calificacion_tienda1}')
print(f' El promedio de calificación de la tienda 2 es: {promedio_calificacion_tienda2}')
print(f' El promedio de calificación de la tienda 3 es: {promedio_calificacion_tienda3}')
print(f' El promedio de calificación de la tienda 4 es: {promedio_calificacion_tienda4}')

 El promedio de calificación de la tienda 1 es: 3.98
 El promedio de calificación de la tienda 2 es: 4.04
 El promedio de calificación de la tienda 3 es: 4.05
 El promedio de calificación de la tienda 4 es: 4.0

# 4. Productos más y menos vendidos

In [156]:
venta_producto_tienda1 = tienda['Producto'].value_counts()
venta_producto_tienda2 = tienda2['Producto'].value_counts()
venta_producto_tienda3 = tienda3['Producto'].value_counts()
venta_producto_tienda4 = tienda4['Producto'].value_counts()

In [155]:
print(f'Se muestra los productos más vendidos de forma ascendente:\n{venta_producto_tienda1}')

Se muestra los productos más vendidos de forma ascendente:
Producto
Microondas                     60
TV LED UHD 4K                  60
Armario                        60
Secadora de ropa               58
Mesa de noche                  56
Bloques de construcción        56
Balón de baloncesto            55
Bicicleta                      54
Vaso térmico                   54
Refrigerador                   54
Impresora                      54
Batería                        53
Cubertería                     52
Carrito de control remoto      52
Modelado predictivo            51
Auriculares                    50
Ajedrez de madera              49
Iphone 15                      49
Lavavajillas                   48
Lavadora de ropa               47
Guitarra eléctrica             47
Guitarra acústica              46
Sofá reclinable                46
Silla de oficina               46
Estufa                         45
Cama box                       44
Kit de bancas                  44
Smart TV                       44
Cama king                      44
Cubo mágico 8x8                44
Mesa de centro                 44
Set de ollas                   43
Smartwatch                     43
Juego de mesa                  43
Balón de voleibol              42
Dashboards con Power BI        42
Tablet ABXY                    42
Sillón                         41
Iniciando en programación      41
Set de vasos                   41
Asistente virtual              40
Muñeca bebé                    40
Mesa de comedor                40
Dinosaurio Rex                 40
Cuerda para saltar             40
Mochila                        39
Ciencia de datos con Python    39
Pandereta                      36
Olla de presión                35
Auriculares con micrófono      33
Celular ABXY                   33
Name: count, dtype: int64

In [157]:
print(f'Se muestra los productos más vendidos de forma ascendente:\n{venta_producto_tienda2}')

Se muestra los productos más vendidos de forma ascendente:
Producto
Iniciando en programación      65
Microondas                     62
Batería                        61
Guitarra acústica              58
Pandereta                      58
Secadora de ropa               57
Iphone 15                      55
Bloques de construcción        54
Armario                        54
Set de ollas                   52
Cuerda para saltar             50
Lavadora de ropa               49
Silla de oficina               49
Refrigerador                   49
Muñeca bebé                    48
Carrito de control remoto      47
Guitarra eléctrica             47
Cama box                       47
Vaso térmico                   47
Modelado predictivo            46
Balón de voleibol              46
Set de vasos                   46
Lavavajillas                   46
Kit de bancas                  45
Cama king                      45
Bicicleta                      45
Mochila                        45
Cubo mágico 8x8                45
Ajedrez de madera              45
Mesa de centro                 45
TV LED UHD 4K                  45
Tablet ABXY                    44
Smartwatch                     44
Mesa de noche                  44
Olla de presión                44
Auriculares con micrófono      44
Sofá reclinable                44
Dashboards con Power BI        43
Ciencia de datos con Python    43
Balón de baloncesto            42
Estufa                         42
Dinosaurio Rex                 42
Celular ABXY                   41
Smart TV                       40
Cubertería                     39
Asistente virtual              38
Auriculares                    37
Sillón                         35
Mesa de comedor                34
Impresora                      34
Juego de mesa                  32
Name: count, dtype: int64

In [158]:
print(f'Se muestra los productos más vendidos de forma ascendente:\n{venta_producto_tienda3}')

Se muestra los productos más vendidos de forma ascendente:
Producto
Kit de bancas                  57
Mesa de comedor                56
Cama king                      56
Set de ollas                   55
Mesa de noche                  55
Smart TV                       54
Estufa                         53
Cuerda para saltar             53
Modelado predictivo            53
Carrito de control remoto      52
Lavavajillas                   52
Bicicleta                      52
Juego de mesa                  52
Pandereta                      51
Impresora                      50
Refrigerador                   50
Balón de baloncesto            50
Armario                        49
Balón de voleibol              48
Tablet ABXY                    48
Sillón                         47
Guitarra acústica              47
Olla de presión                47
Ajedrez de madera              47
Ciencia de datos con Python    46
Iphone 15                      46
Dinosaurio Rex                 46
Silla de oficina               46
Smartwatch                     46
Cama box                       46
Iniciando en programación      46
Secadora de ropa               45
Sofá reclinable                45
Celular ABXY                   44
Cubo mágico 8x8                44
Auriculares                    43
TV LED UHD 4K                  42
Mesa de centro                 42
Lavadora de ropa               42
Batería                        41
Dashboards con Power BI        40
Cubertería                     39
Muñeca bebé                    39
Auriculares con micrófono      39
Asistente virtual              39
Vaso térmico                   38
Guitarra eléctrica             38
Set de vasos                   36
Mochila                        36
Microondas                     36
Bloques de construcción        35
Name: count, dtype: int64

In [159]:
print(f'Se muestra los productos más vendidos de forma ascendente:\n{venta_producto_tienda4}')

Se muestra los productos más vendidos de forma ascendente:
Producto
Cama box                       62
Cubertería                     59
Dashboards con Power BI        56
Cama king                      56
Carrito de control remoto      55
Mesa de comedor                55
Mesa de noche                  55
Smart TV                       54
Bloques de construcción        54
Pandereta                      52
Impresora                      50
Modelado predictivo            50
Asistente virtual              50
Set de ollas                   50
Balón de baloncesto            50
Vaso térmico                   48
Iphone 15                      48
Muñeca bebé                    48
Batería                        48
Balón de voleibol              48
Juego de mesa                  48
Microondas                     48
Estufa                         47
Cubo mágico 8x8                47
Sofá reclinable                47
Dinosaurio Rex                 47
Olla de presión                46
Set de vasos                   46
Tablet ABXY                    45
Sillón                         45
Bicicleta                      45
Mesa de centro                 44
Auriculares                    44
Lavavajillas                   43
Cuerda para saltar             43
Iniciando en programación      43
Mochila                        43
Auriculares con micrófono      42
Kit de bancas                  42
TV LED UHD 4K                  40
Secadora de ropa               40
Silla de oficina               40
Celular ABXY                   39
Ajedrez de madera              39
Smartwatch                     39
Lavadora de ropa               38
Refrigerador                   38
Ciencia de datos con Python    38
Guitarra acústica              37
Armario                        34
Guitarra eléctrica             33
Name: count, dtype: int64

In [164]:
producto_menos_vendidos_tienda1 = tienda['Producto'].value_counts()
producto_menos_vendidos_tienda1

Producto
Microondas                     60
TV LED UHD 4K                  60
Armario                        60
Secadora de ropa               58
Mesa de noche                  56
Bloques de construcción        56
Balón de baloncesto            55
Bicicleta                      54
Vaso térmico                   54
Refrigerador                   54
Impresora                      54
Batería                        53
Cubertería                     52
Carrito de control remoto      52
Modelado predictivo            51
Auriculares                    50
Ajedrez de madera              49
Iphone 15                      49
Lavavajillas                   48
Lavadora de ropa               47
Guitarra eléctrica             47
Guitarra acústica              46
Sofá reclinable                46
Silla de oficina               46
Estufa                         45
Cama box                       44
Kit de bancas                  44
Smart TV                       44
Cama king                      44
Cubo mágico 8x8                44
Mesa de centro                 44
Set de ollas                   43
Smartwatch                     43
Juego de mesa                  43
Balón de voleibol              42
Dashboards con Power BI        42
Tablet ABXY                    42
Sillón                         41
Iniciando en programación      41
Set de vasos                   41
Asistente virtual              40
Muñeca bebé                    40
Mesa de comedor                40
Dinosaurio Rex                 40
Cuerda para saltar             40
Mochila                        39
Ciencia de datos con Python    39
Pandereta                      36
Olla de presión                35
Auriculares con micrófono      33
Celular ABXY                   33
Name: count, dtype: int64

In [165]:
producto_menos_vendidos_tienda2 = tienda2['Producto'].value_counts()
producto_menos_vendidos_tienda2

Producto
Iniciando en programación      65
Microondas                     62
Batería                        61
Guitarra acústica              58
Pandereta                      58
Secadora de ropa               57
Iphone 15                      55
Bloques de construcción        54
Armario                        54
Set de ollas                   52
Cuerda para saltar             50
Lavadora de ropa               49
Silla de oficina               49
Refrigerador                   49
Muñeca bebé                    48
Carrito de control remoto      47
Guitarra eléctrica             47
Cama box                       47
Vaso térmico                   47
Modelado predictivo            46
Balón de voleibol              46
Set de vasos                   46
Lavavajillas                   46
Kit de bancas                  45
Cama king                      45
Bicicleta                      45
Mochila                        45
Cubo mágico 8x8                45
Ajedrez de madera              45
Mesa de centro                 45
TV LED UHD 4K                  45
Tablet ABXY                    44
Smartwatch                     44
Mesa de noche                  44
Olla de presión                44
Auriculares con micrófono      44
Sofá reclinable                44
Dashboards con Power BI        43
Ciencia de datos con Python    43
Balón de baloncesto            42
Estufa                         42
Dinosaurio Rex                 42
Celular ABXY                   41
Smart TV                       40
Cubertería                     39
Asistente virtual              38
Auriculares                    37
Sillón                         35
Mesa de comedor                34
Impresora                      34
Juego de mesa                  32
Name: count, dtype: int64

In [166]:
producto_menos_vendidos_tienda3 = tienda3['Producto'].value_counts()
producto_menos_vendidos_tienda3

Producto
Kit de bancas                  57
Mesa de comedor                56
Cama king                      56
Set de ollas                   55
Mesa de noche                  55
Smart TV                       54
Estufa                         53
Cuerda para saltar             53
Modelado predictivo            53
Carrito de control remoto      52
Lavavajillas                   52
Bicicleta                      52
Juego de mesa                  52
Pandereta                      51
Impresora                      50
Refrigerador                   50
Balón de baloncesto            50
Armario                        49
Balón de voleibol              48
Tablet ABXY                    48
Sillón                         47
Guitarra acústica              47
Olla de presión                47
Ajedrez de madera              47
Ciencia de datos con Python    46
Iphone 15                      46
Dinosaurio Rex                 46
Silla de oficina               46
Smartwatch                     46
Cama box                       46
Iniciando en programación      46
Secadora de ropa               45
Sofá reclinable                45
Celular ABXY                   44
Cubo mágico 8x8                44
Auriculares                    43
TV LED UHD 4K                  42
Mesa de centro                 42
Lavadora de ropa               42
Batería                        41
Dashboards con Power BI        40
Cubertería                     39
Muñeca bebé                    39
Auriculares con micrófono      39
Asistente virtual              39
Vaso térmico                   38
Guitarra eléctrica             38
Set de vasos                   36
Mochila                        36
Microondas                     36
Bloques de construcción        35
Name: count, dtype: int64

In [167]:
producto_menos_vendidos_tienda4 = tienda4['Producto'].value_counts()
producto_menos_vendidos_tienda4

Producto
Cama box                       62
Cubertería                     59
Dashboards con Power BI        56
Cama king                      56
Carrito de control remoto      55
Mesa de comedor                55
Mesa de noche                  55
Smart TV                       54
Bloques de construcción        54
Pandereta                      52
Impresora                      50
Modelado predictivo            50
Asistente virtual              50
Set de ollas                   50
Balón de baloncesto            50
Vaso térmico                   48
Iphone 15                      48
Muñeca bebé                    48
Batería                        48
Balón de voleibol              48
Juego de mesa                  48
Microondas                     48
Estufa                         47
Cubo mágico 8x8                47
Sofá reclinable                47
Dinosaurio Rex                 47
Olla de presión                46
Set de vasos                   46
Tablet ABXY                    45
Sillón                         45
Bicicleta                      45
Mesa de centro                 44
Auriculares                    44
Lavavajillas                   43
Cuerda para saltar             43
Iniciando en programación      43
Mochila                        43
Auriculares con micrófono      42
Kit de bancas                  42
TV LED UHD 4K                  40
Secadora de ropa               40
Silla de oficina               40
Celular ABXY                   39
Ajedrez de madera              39
Smartwatch                     39
Lavadora de ropa               38
Refrigerador                   38
Ciencia de datos con Python    38
Guitarra acústica              37
Armario                        34
Guitarra eléctrica             33
Name: count, dtype: int64

# 5. Envío promedio por tienda

In [186]:
promedio_envio_tienda1 = tienda['Costo de envío'].mean()
promedio_envio_tienda2 = tienda2['Costo de envío'].mean()
promedio_envio_tienda3 = tienda3['Costo de envío'].mean()
promedio_envio_tienda4 = tienda4['Costo de envío'].mean()

In [194]:
print(f'El promedio de envío de la tienda 1 es: {promedio_envio_tienda1}')
print(f'El promedio de envío de la tienda 2 es: {promedio_envio_tienda2}')
print(f'El promedio de envío de la tienda 3 es: {promedio_envio_tienda3}')
print(f'El promedio de envío de la tienda 4 es: {promedio_envio_tienda4}')

El promedio de envío de la tienda 1 es: 26018.60958033065
El promedio de envío de la tienda 2 es: 25216.235693090293
El promedio de envío de la tienda 3 es: 24805.680373039424
El promedio de envío de la tienda 4 es: 23459.457167090754

###Gráficos

In [212]:
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter